pipeline {
    agent {
        dockerfile {
            filename 'jenkins/Dockerfile'  // Path to the custom Dockerfile that includes kubectl
            dir '.'                        // Build context root
        }
    }

    environment {
        IMAGE_NAME = 'student-survey-flask-app'
        IMAGE_TAG = 'latest'
        DOCKER_USER = 'ruchitadarur'
    }

    stages {
        stage('Login to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    sh 'echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('student-survey-flask-app') {
                    sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
                }
            }
        }

        stage('Tag & Push to Docker Hub') {
            steps {
                dir('student-survey-flask-app') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                        sh '''
                            docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
                            docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG
                        '''
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-id', variable: 'KUBECONFIG')]) {
                    sh 'kubectl apply -f student-survey-flask-app/kubernetes/'
                }
            }
        }
    }
}
