apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-app
  labels:
    app: student-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: miruthula14/student-survey-flask-app:latest
        ports:
        - containerPort: 5000
