apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  selector:
    app: student-survey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
